pipeline {
    agent any
    stages {
        stage('build with unit test, package and store the jar') {
            steps {
            	echo 'Building app...'
                sh 'mvn -U -f bookstore_app clean install -Dintegration-tests.skip=true'
                //sh 'mvn -f bookstore_app -Pbuild clean install  -Dskip.it=true'
            }
        }
        
        stage('deploy app') {
            steps {
            	echo 'Deploying app...'            	
                // shutdown
			    sh 'curl -X POST http://localhost:8080/shutdown || true'
			    // start the application
				sh 'ls -l bookstore_app/bookstore-integration-test/target/classes/bookstore-server-0.0.1-SNAPSHOT.jar'
                sh 'nohup java -jar bookstore_app/bookstore-integration-test/target/classes/*.jar &'			   
                //sh 'cat nohup.out'                            
            }
        }
        
        stage('run integration tests') {
            steps {
            	echo 'Running integration tests...'
                sh 'mvn -f bookstore_app verify -Dunit-tests.skip=true'
            	//sh 'mvn -f bookstore_app -Pintegration clean test -DskipUTs'
            }
        }
    }
}
